# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
final_space: true
version: 2
blocks:
  - type: prompt
    alignment: left
    segments:
      - type: time
        style: plain
        foreground: "green"
        properties:
          time_format: Monday 02.01.2006
      - type: path
        style: plain
        foreground: "blue"
        properties:
          style: full
      - type: text
        style: plain
        foreground: "#E06C75"
        template: ❯
