# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
final_space: true
version: 2
blocks:
  - type: prompt
    alignment: left
    segments:
      - type: time
        style: plain
        foreground: "green"
        template: "{{ .CurrentDate | date .Format }} "
        properties:
          time_format: Monday 02.01.2006
      - type: path
        style: plain
        foreground: "blue"
        template: "{{ .Path }} "
        properties:
          style: full
      - type: status
        style: diamond
        trailing_diamond: " "
        leading_diamond: 
        foreground: "#ffffff"
        background: "red"
        template: " {{ .String }}"
        properties:
          always_enabled: false
      - type: text
        style: plain
        foreground: "#E06C75"
        template: ""
  - type: rprompt
    alignment: right
    segments:
      - type: executiontime
        style: diamond
        trailing_diamond: " "
        leading_diamond: 
        foreground: "#ffffff"
        background: "yellow"
        template: " {{ .FormattedMs }}"
        properties:
          threshold: 500
          style: austin
