"                                     VIM
" =============================================================================
set encoding=utf8
set number
set nowrap
set nobackup
set cursorline
set nowritebackup
set noswapfile
set laststatus=2
set clipboard=unnamedplus
set autoread
set hidden
set ignorecase
set smartcase
set incsearch
set hlsearch
set autoindent
set secure
set bomb
set nocompatible
set termguicolors
set completeopt=
set belloff=all
set nolist
set listchars=tab:»·
set history=5000
set shm+=I
set cinoptions=N-s,g0
set title
set list
if !has('nvim')
	set noesckeys
endif

filetype plugin indent on
syntax enable
let mapleader="\<space>"

command! Vb normal! <C-v>

nmap <F11> :call GuiWindowFullScreen(!g:GuiWindowFullScreen)<cr>
nmap <C-s> :w<cr>
nmap <Space>s :w<cr>
nmap go <C-o>
nmap gnh :noh<cr>
map <C-n> :cn<cr>
map <C-p> :cp<cr>
vnoremap <Tab> > gv
vnoremap <S-Tab> < gv
imap <C-s> <esc>:w<cr>
inoremap <C-o> <C-x><C-o>

nnoremap gj <C-w>j
nnoremap gk <C-w>k
nnoremap gl <C-w>l
nnoremap gh <C-w>h

nmap <Space>v :vsp<cr>
nmap <Space>a :A<cr>

if has('nvim')
	autocmd TermOpen * setlocal nonumber
	tnoremap <Esc> <C-\><C-n>
	tnoremap <C-v><Esc> <Esc>
endif

autocmd FileType qf wincmd J
autocmd FileType qf resize 15
autocmd FileType qf setlocal nocursorline

autocmd BufNewFile,BufRead *.xaml setf xml
autocmd BufRead,BufNewFile *.swift set filetype=swift
autocmd filetype cs :setlocal syntax=off
autocmd VimEnter * :clearjumps

"                                  FZF(.vim)
" =============================================================================
set rtp+=/usr/local/opt/fzf
nmap <Space>h :History:<cr>
nmap <Space>c :Commands<cr>
nmap <Space>b :Buffers<cr>
nmap <Space>f :Files<cr>

if has('nvim')
	autocmd FileType fzf tnoremap <buffer> <Esc> <Esc>
endif
"                                  DevIcons
" =============================================================================
let WebDevIconsUnicodeDecorateFolderNodesExactMatches = 0
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols = {}
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['cs'] = ''
let g:DevIconsEnableFoldersOpenClose = 1
let g:DevIconsDefaultFolderOpenSymbol=''
let g:WebDevIconsUnicodeDecorateFolderNodesDefaultSymbol=''

"                                  NERDTree
" =============================================================================
"
let g:NERDTreeIgnore=['.*obj$[[dir]]', '.*bin$[[dir]]']
let g:NERDTreeHijackNetrw=1
let g:NERDTreeDirArrowCollapsible=''
let g:NERDTreeDirArrowExpandable=''
let g:NERDTreeCreatePrefix='silent keepalt keepjumps'
let g:NERDTreeMinimalUI=1
let g:NERDTreeCascadeSingleChildDir=0

nmap <Space>e :e .<cr>

autocmd filetype nerdtree highlight folder_icon guifg=#3daee9 guibg=NONE
autocmd filetype nerdtree highlight csharp_icon guifg=#88d184 guibg=NONE
autocmd filetype nerdtree highlight solution_icon guifg=#d294e2 guibg=NONE
autocmd filetype nerdtree highlight batch_icon guifg=#82aef7 guibg=NONE
autocmd filetype nerdtree highlight vim_icon guifg=#6ed65f guibg=NONE
autocmd filetype nerdtree highlight swift_icon guifg=#fa5637 guibg=NONE
autocmd filetype nerdtree highlight rust_icon guifg=#ff8170 guibg=NONE
autocmd filetype nerdtree highlight cxx_header_icon guifg=#11d116 guibg=NONE
autocmd filetype nerdtree highlight cxx_source_icon guifg=#11d116 guibg=NONE
autocmd filetype nerdtree highlight link script_icon csClass

autocmd filetype nerdtree syn match script_icon /  / containedin=NERDTreeFlags
autocmd filetype nerdtree syn match folder_icon /  / containedin=NERDTreeFlags
autocmd filetype nerdtree syn match folder_icon /  / containedin=NERDTreeFlags
autocmd filetype nerdtree syn match vim_icon /  / containedin=NERDTreeFlags
autocmd filetype nerdtree syn match csharp_icon /  / containedin=NERDTreeFlags
autocmd filetype nerdtree syn match cxx_header_icon /  / containedin=NERDTreeFlags
autocmd filetype nerdtree syn match cxx_source_icon /  / containedin=NERDTreeFlags
autocmd filetype nerdtree syn match swift_icon /  / containedin=NERDTreeFlags
autocmd filetype nerdtree syn match solution_icon /  / containedin=NERDTreeFlags
autocmd filetype nerdtree syntax match NERDTreeDirSlash #/$# containedin=NERDTreeDir conceal contained
autocmd filetype nerdtree syn match rust_icon /  / containedin=NERDTreeFlags
"                                 Omnisharp
" =============================================================================
"
let g:OmniSharp_highlighting = 1
let g:OmniSharp_server_stdio = 1
let g:OmniSharp_highlight_debug = 0
let g:OmniSharp_diagnostic_showid = 0
let g:OmniSharp_loglevel = 'none'
let g:OmniSharp_want_snippet = 1
let g:OmniSharp_highlight_groups = {
\ 'csString': ['string', "string - verbatim"],
\ 'csClass': ['class name'],
\ 'csDelegateName': ['delegate name'],
\ 'csKeyword': ['keyword', 'keyword - control'],
\ 'csComment': [
    \ 'comment',
    \ 'xml doc comment - text',
    \ 'xml doc comment - name',
    \ 'xml doc comment - delimiter'
    \ ],
\ 'csStruct': ['struct name'],
\ 'csInterface': ['interface name'],
\ 'csNumber': ['number'],
\ 'csEnum': ['enum name'],
\ 'csEnumMemberName': ['enum member name'],
\ 'csPreprocessor' : [ 'preprocessor keyword', 'preprocessor text' ],
\ 'csTypeParamName': ['type parameter name'],
\ 'csExcludedCode': ['excluded code'],
\}
let g:OmniSharp_popup_options = {
\ 'highlight': 'Normal',
\ 'padding': [1, 2, 1, 2],
\ 'border': [1, 1, 1, 1],
\ 'borderchars': ['─', '│', '─', '│', '╭', '╮', '╯', '╰' ]
\}

nmap <C-q> :OmniSharpGetCodeActions<cr>
nmap gd :OmniSharpGotoDefinition<cr>

"                                  AutoPairs
" =============================================================================
let g:AutoPairsShortcutToggle=''
let g:AutoPairs = {
\   '\w\zs<':'>',
\   '(':')',
\   '[':']',
\   '{':'}',
\   "'":"'",
\   '"':'"',
\   "`":"`",
\}
command! ToggleAutoPairs :call AutoPairsToggle()

"                                   cursorword
" =============================================================================
"
let g:cursorword_delay=800
let g:cursorword=0

"                                   A.vim
" =============================================================================
"
let g:alternateNoDefaultAlternate=1

"                                EditorConfig
" =============================================================================
"
let g:EditorConfig_exclude_patterns = ['fugitive://.*', 'scp://.*']
au FileType gitcommit let b:EditorConfig_disable = 1

"                                   minPack
" =============================================================================
"
packadd minpac
call minpac#init()
call minpac#add('k-takata/minpac', {'type': 'opt'})
call minpac#add('jiangmiao/auto-pairs')
call minpac#add('junegunn/fzf.vim')
call minpac#add('SirVer/ultisnips')
call minpac#add('scrooloose/nerdtree')
call minpac#add('OmniSharp/omnisharp-vim')
call minpac#add('ryanoasis/vim-devicons')
call minpac#add('rust-lang/rust.vim')
call minpac#add('tpope/vim-fugitive')
call minpac#add('mbbill/undotree')
call minpac#add('tpope/vim-commentary')
call minpac#add('cespare/vim-toml')
call minpac#add('peterhoeg/vim-qml')
call minpac#add('itchyny/vim-cursorword')
call minpac#add('kassio/neoterm')
call minpac#add('neovim/nvim-lspconfig')
call minpac#add('vim-scripts/a.vim')
call minpac#add('vim-scripts/a.vim')
call minpac#add('editorconfig/editorconfig-vim')
command! PackUpdate call minpac#update()
command! PackClean call minpac#clean()

"                                   LUA stuff
" =============================================================================
"
lua << EOF
local function lspSymbol(name, icon)
vim.fn.sign_define(
	'DiagnosticSign' .. name,
	{ text = icon, texthl = 'DiagnosticSign' .. name }
)
end
lspSymbol('Error', '')
lspSymbol('Warn', '')
lspSymbol('Info', '')
lspSymbol('Hint', '')
EOF

colorscheme mine
